.github/workflows/ci.yml
tests/test_operator_registry.py

set GitHub action to trigger CI when there is a PR to `main` branch instead of the old `prototype` branch

ci: run ci when pushed to main

---

dev/release.sh
poetry.lock
pyproject.toml

using poetry to pin all our dependencies.  #45 
poetry is used for:
- managing the dependency version
- managing building and publishing to pypi

feat: using poetry to manage dependencies

---

bentoctl/operator/registry.py
tests/test_operator_registry.py

when adding an operator from path, use that path in the registry instead of copying over the files to `$HOME/bentoctl`. This is to ensure maximum flexibility for devs creating operators.

feat: use existing path in operator registy in case of local operator install

---

bentoctl/cli/__init__.py
bentoctl/deployment_config.py

- also don't print out the description in case the `describe()` function returns `None`. This is in case operators print the description themselves without parsing.

fix: 'type' is not a required value for the schema

---

bentoctl/__init__.py
bentoctl/cli/__init__.py
poetry.lock
pyproject.toml

- bentoctl --version and `bentoctl.__version__` for getting the version of the bentoctl package
- Single source for the bentoctl package version which is the `pyproject.toml` file `tool.poetry.version`. This is to be updated with the `poetry version` command.

__version__ for bentoctl package

---

bentoctl/cli/__init__.py
bentoctl/cli/utils.py
bentoctl/deployment_config.py
bentoctl/exceptions.py

fix: added proper exception handling

---

bentoctl/cli/__init__.py

Update cli build command

---

bentoctl/deployment_config.py

`make lint` script have passed

fix: incorrect generated image tag for bentoctl

---

codecov.yaml

Update the Code Cov settings to be more liberal with Patch and Coverage

ci: updated codecov settings

---

bentoctl/cli/__init__.py
bentoctl/console.py
tests/unit/cli/test_cli_basic.py

Show the help message after the `bentoctl build command has been run.
How it looks in the terminal
closes:  #112

feat: help message post build command

---

docs/quickstart.md

Update quickstart.md with required pip package

---

bentoctl/deployment_config.py
bentoctl/exceptions.py

Improve the help message by showing the Exception class name along with the exception message
closes:

feat: error message string now shows Exception name

---

poetry.lock
pyproject.toml

The current changes with the latest bentoml release breaks 3 operators
1. aws-lambda
2. aws-sagemaker
3. azure-functions
We are working on the fixes but in the mean time we are pinning it to previous version until we merge the changes into the operator
closes:

fix: pin bentoml version to 1.0.0a7

---

Makefile
bentoctl/cli/__init__.py
bentoctl/cli/utils.py
bentoctl/deployment_config.py
bentoctl/docker_utils.py
bentoctl/operator/operator.py
bentoctl/operator/registry.py
bentoctl/utils/__init__.py
bentoctl/utils/operator_helpers/utils.py
bentoctl/utils/temp_dir.py
bentoctl/utils/usage_stats.py
codecov.yaml
dev/release.sh
poetry.lock
pyproject.toml
tests/conftest.py
tests/unit/cli/test_cli_basic.py
tests/unit/operator/test_operator.py
tests/unit/operator/test_operator_registry.py

Signed-off-by: Aaron Pham <29749331+aarnphm@users.noreply.github.com>
- refactor to using buildx from bentoml
- add Makefile to format code with isort and black
- operator should now only return the `dockerfile` and the `context_path`
- `TempDirectory` context manager returns a `Path` instead of string 
closes: #165
also fix analytics issues that failed ci tests

refactor: using buildx and add format

---

ci/unit_tests.sh
pyproject.toml
tests/README.md
tests/integration/conftest.py
tests/integration/test_service.py
tests/testbento/bentofile.yaml
tests/testbento/service.py
tests/testbento/train.py

The test bento has different endpoints and runner to test out an extreme version of the bentoml a user might run. There is also tests under `tests/integration` that will perform an integration test on these.
closes:

test: added a test script and bento for easier end2end testing

---

bentoctl/cli/operator_management.py
bentoctl/operator/registry.py

- changed `operator remove` command to `operator uninstall` to make it more intuitive to the opposite command `operator install`
- Fixed the update workflow. Now `operator update <operator-name>` will update the operator to the latest version.
closes:

fix: update flow

---

.github/workflows/ci.yml
bentoctl/cli/utils.py
bentoctl/utils/usage_stats.py

Curently bentoctl CliEvent is not defined with attrs and hence does not get serialized completely 
when calling `track()` function in bentoml.
closes:

fix: calling the bentoml's track() with incorrect CliEvent

---

bentoctl/docker_utils.py

loads the final image build into system-wide docker. This fixes the docker image missing error when the docker buildx builder is a container-based one. @ssheng had experienced this issue on his system
closes:

fix: pass the --load flag with buildx build to make result img available

---

bentoctl/cli/__init__.py
bentoctl/cli/interactive.py
bentoctl/deployment_config.py
tests/unit/cli/test_interactive.py

See here for context: https://github.com/bentoml/google-cloud-run-deploy/pull/21#discussion_r984038740
UI:
Select `y`:
Enter `BENTOML_CONFIG_OPTIONS`:
Enter `api_server.workers=1`:
Select `n`:
closes:

feat(config): add `env` block to deployment config

---

.github/CODEOWNERS

This PR tries to add CODEOWNERS for bentoctl. Maybe we can also pull in more member to
maintain bentoctl with @jjmachan
Signed-off-by: Aaron Pham <29749331+aarnphm@users.noreply.github.com>

chore: adding codeowners for bentoctl

---

poetry.lock
pyproject.toml

This PR tries to relax the restriction for PyYAML and docker.
I'm not entirely sure the reason for locking this modules before. 
cc @jjmachan ?
Signed-off-by: Aaron Pham <29749331+aarnphm@users.noreply.github.com>

chore: relax pypi restriction

---

tests/testbento/bentofile.yaml

test: add pydantic requirement to test-bento
